# Generated by Django 4.1.7 on 2023-03-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('a', 'Available'), ('r', 'Reserverd'), ('o', 'On loan')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
