# Generated by Django 4.1.7 on 2023-03-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_bookinstance_options_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserverd'), ('a', 'Available'), ('m', 'Maintenance'), ('o', 'On loan')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
